### ISSUE TITLE
Support for Winbond Nand flash

### ISSUE THREAD

**Issue by karimulla1993** [lllucius/esp32_fatflash#1]
Does this component support the Winbond Nand flash ?? I am using W25M02G

**Comment by lllucius** [comment]
Not entirely sure, but the command set looks similar to other Winbond chips.  It looks like it only supports a 128KB erase though, so if you plan to use it with the ESP32 VFS filesystems, it's going to be tricky as you'll need to a 128KB buffer.

**Comment by karimulla1993** [comment]
@lllucius , Thanks for quick reply . yes it supports Uniform 128K-Byte Block Erase. Does it support your esp32_extflash ?

**Comment by lllucius** [comment]
Yes, esp32_extflash could be modified to support that chip.  You could use the w25q classes as a guide to create a custom class that incorporates any specific changes for your chip.

**Comment by karimulla1993** [comment]
ok, Thanks , I will work on that
