### ISSUE TITLE
hit watchdog while formating

### ISSUE THREAD

**Issue by alsaleem00** [lllucius/esp32_fatflash#3]
Hi,
I connected a 25Q128FVSG NOR Flash to ESP32 module and configured the ext-flash accordingly.

ext-flash is detecting the correct size and capacity. 
`            if (id[2] >= 0x10 && id[2] <= 0x19)
            {
                capacity = 1 << id[2];
            }
`
Now, when fatflash is formatting the flash, always hits the watchdog.
I am getting :
`rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)`

I tried to init from main(), and also tried with a separate task, but always hit watchdog.

Is there a solution to do formatting in discontinued manner as to allow OS to update watchdog.

Thanks

**Comment by lllucius** [comment]
You could use "Extflash::erase_range()" in a loop while satisfying the watchdog.  It'll be a little slower.  Or you could dot the erase in a thread with the main thread satisfying the watchdog.

**Comment by alsaleem00** [comment]
I found the problem:
at (fatflash.cpp) line 69, when the function is called
`    err = flash->init();
`
the task hangs which causes CPU to restart. I believe that it was caused by not specifying the dma size
`    .max_dma_size = 0, //SPI_MAX_DMA_LEN,
` 
After explicitly specifying the **.max_dma_size** member in **ext_flash_config_t** with (SPI_MAX_DMA_LEN), it goes through. Now, I can list dir, read/write files normally

Maybe you need to note this in next release! Also please add support for 128Mb/256Mb
Thanks.

**Comment by lllucius** [comment]
I will definitely so something about it if I EVER get a chance to work on this stuff again.  I really do need to jettison the real job.  :-)
